
Dataset not found ⚠️, missing paths ['/home/oliver_welsh/Oliver_Welsh/Code/GitHub/Image-Processing-Project/yolov5/data/training_data/images/val']
Traceback (most recent call last):
  File "/home/oliver_welsh/Oliver_Welsh/Code/GitHub/Image-Processing-Project/yolov5/train.py", line 986, in <module>
    main(opt)
  File "/home/oliver_welsh/Oliver_Welsh/Code/GitHub/Image-Processing-Project/yolov5/train.py", line 688, in main
    train(opt.hyp, opt, device, callbacks)
  File "/home/oliver_welsh/Oliver_Welsh/Code/GitHub/Image-Processing-Project/yolov5/train.py", line 203, in train
    data_dict = data_dict or check_dataset(data)  # check if None
  File "/home/oliver_welsh/Oliver_Welsh/Code/GitHub/Image-Processing-Project/yolov5/utils/general.py", line 565, in check_dataset
    raise Exception("Dataset not found ❌")
Exception: Dataset not found ❌
Traceback (most recent call last):
  File "/home/oliver_welsh/Oliver_Welsh/Code/GitHub/Image-Processing-Project/yolov5/train.py", line 986, in <module>
    main(opt)
  File "/home/oliver_welsh/Oliver_Welsh/Code/GitHub/Image-Processing-Project/yolov5/train.py", line 688, in main
    train(opt.hyp, opt, device, callbacks)
  File "/home/oliver_welsh/Oliver_Welsh/Code/GitHub/Image-Processing-Project/yolov5/train.py", line 203, in train
    data_dict = data_dict or check_dataset(data)  # check if None
  File "/home/oliver_welsh/Oliver_Welsh/Code/GitHub/Image-Processing-Project/yolov5/utils/general.py", line 565, in check_dataset
    raise Exception("Dataset not found ❌")
Exception: Dataset not found ❌
